export const defaultTasksAttributesFilter = {
  name: undefined,
  checked: false,
  important: false,
  id: "",
  title: "",
  status: "",
  requester: "",
  company: "",
  assignedTo: "",
  createdAt: "",
  deadline: "",
  project: "",
  milestone: "",
  taskType: "",
  overtime: "",
  pausal: "",
  tags: "",
  subtasksApproved: "",
  subtasksPending: "",
  tripsApproved: "",
  tripsPending: "",
  materialsApproved: "",
  materialsPending: "",
  itemsApproved: "",
  itemsPending: "",
}
export const defaultTaskSort = {
  key: 'status',
  asc: true
}

export const defaultTasklistColumnPreference = {
  taskId: true,
  status: true,
  important: true,
  invoiced: true,
  title: true,
  requester: true,
  company: true,
  assignedTo: true,
  createdAtV: false,
  deadline: true,
  project: true,
  milestone: false,
  taskType: false,
  overtime: false,
  pausal: false,
  tags: false,
  subtasksApproved: false,
  subtasksPending: false,
  tripsApproved: false,
  tripsPending: false,
  materialsApproved: false,
  materialsPending: false,
  itemsApproved: false,
  itemsPending: false,
}