//Attributes passed to ShowData as props

const props = {
  link,
  match,
  history,
  itemID,
  displayCol,
  Empty,
  Edit,
  setLayout,
  layout,
  showLayoutSwitch,
  breadcrumsData,
  useBreadcrums,
  listName,
  orderByValues,
  orderBy,
  ascending,
  filterBy,
  generalSearch,
  useVisibility,
  setVisibility,
  displayValues,
  setOrderBy,
  setAscending,
  setGeneralSearch,
  defaultAttributesFilter,
  attributesFilter,
  setAttributeFilter,
  setAttributesFilter,
  currentUser,
  checkItem,
  deleteMultiple,
  canDeleteMultiple,
  MultipleEdit,
  canEditMultiple
}